name = "nearcard-worker"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[vars]
FRONTEND_URL = "https://nearcard-app.pages.dev"

[[d1_databases]]
binding = "DB"
database_name = "nearcard-db"
database_id = "d90db67f-7ab4-4e8f-832c-4b83a0caaa06"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "nearcard-avatars"
